# Generated by Django 4.2.9 on 2024-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_department_options_alter_position_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/default.jpg', upload_to='media/users/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
