# Generated by Django 4.2.9 on 2024-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/profile_default.jpg', upload_to='media/users/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
