# Generated by Django 4.2.9 on 2024-07-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='path_ou',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='OU'),
        ),
    ]
