# Generated by Django 4.2.9 on 2024-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_position_path_ou'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('crt', 'Запрошен'), ('act', 'Активен'), ('blk', 'Блокирован')], default='crt', max_length=3, verbose_name='Статус'),
        ),
    ]
