# Generated by Django 4.2.9 on 2024-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_start_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
