# Generated by Django 4.2.9 on 2024-07-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
